# Generated by Django 2.0.1 on 2018-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.CharField(max_length=5, unique=True)),
                ('number_licenses', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(0, 'Desabilitado'), (1, 'Habilitado'), (2, 'Demonstração')], default=0, max_length=1)),
            ],
        ),
    ]
