# Generated by Django 2.0.1 on 2018-01-31 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveSmallIntegerField(choices=[(0, '4K'), (1, 'HD 1080'), (2, 'HD 720'), (3, '480'), (4, '360'), (5, '270')], default=3)),
                ('url', models.URLField()),
                ('fileName', models.CharField(max_length=50, unique=True)),
                ('fileHash', models.CharField(max_length=50, unique=True)),
                ('sizeKB', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Indisponivel'), (1, 'Disponivel')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('hiresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('lowresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(null=True)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('posterURL', models.ImageField(upload_to='poster/')),
                ('thumbsURL', models.ImageField(upload_to='thumbs/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('numberLicenses', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado'), (2, 'Demonstração')], default=0)),
                ('channel', models.ManyToManyField(to='video.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='video.Block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(0, 'Informação'), (1, 'Erro'), (2, 'Aviso')], default=0)),
                ('eventDescription', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('style', models.PositiveSmallIntegerField(choices=[(0, 'Critical'), (1, 'Query'), (2, 'Warning'), (3, 'Information')], default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='video.Channel'),
        ),
        migrations.AddField(
            model_name='block',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip', to='video.Clip'),
        ),
    ]
