# Generated by Django 2.0.1 on 2018-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='number_licenses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado'), (2, 'Demonstração')], default=0, max_length=1),
        ),
    ]
