# Generated by Django 2.0.1 on 2018-01-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180129_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
