# Generated by Django 2.0.1 on 2018-01-29 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('hiresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('lowresLifetime', models.PositiveSmallIntegerField(default=0)),
                ('logoUrl', models.CharField(max_length=150, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado'), (2, 'Demonstração')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.DateTimeField(null=True)),
                ('length', models.PositiveSmallIntegerField(default=0)),
                ('posterURL', models.ImageField(upload_to='poster/')),
                ('thumbsURL', models.ImageField(upload_to='thumbs/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='video.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('numberLicenses', models.PositiveSmallIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Desabilitado'), (1, 'Habilitado'), (2, 'Demonstração')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(0, 'Informação'), (1, 'Erro'), (2, 'Aviso')], default=0)),
                ('eventDescription', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationDescription', models.CharField(max_length=250)),
                ('style', models.PositiveSmallIntegerField(choices=[(0, 'Critical'), (1, 'Query'), (2, 'Warning'), (3, 'Information')], default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
