# Generated by Django 2.0.1 on 2018-01-30 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_channel_clip_company_log_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.PositiveSmallIntegerField(choices=[(0, '4K'), (1, 'HD 1080'), (2, 'HD 720'), (3, '480'), (4, '360'), (5, '270')], default=3)),
                ('url', models.URLField()),
                ('fileName', models.CharField(max_length=50, unique=True)),
                ('fileHash', models.CharField(max_length=50, unique=True)),
                ('sizeKB', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Indisponivel'), (1, 'Disponivel')], default=1)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='video.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='video.Block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifyByEmail', models.BooleanField()),
                ('roles', models.PositiveSmallIntegerField(choices=[(0, 'Espectador'), (1, 'Editor'), (2, 'Gerente'), (3, 'Administrador')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='video.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notificationDescription',
            new_name='description',
        ),
    ]
